apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  generation: 4
  labels:
    app: blind-spot
  name: blind-spot
  namespace: default
  resourceVersion: "183459"
  selfLink: /apis/apps/v1/namespaces/default/deployments/blind-spot
  uid: 8a7afcef-6974-11ea-bef9-42010a8e01a8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: blind-spot
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: blind-spot
    spec:
      containers:
      - image: gcr.io/poli-bias-project/poli-bias-img
        imagePullPolicy: Always
        name: poli-bias-img
        resources:
          limits:
            cpu: 1500m
            memory: 12Gi
          requests:
            cpu: 1000m
            memory: 8Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
